/*

 BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : C:\users\aarongiroux\Desktop\brick.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmapWidth 40
#define backgroundmapHeight 36
#define backgroundmapBank 0

extern unsigned char backgroundmap[];

/* End of BG.H */
